# Generated by Django 2.1.5 on 2019-04-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_orangecap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrangeCap',
        ),
    ]
